import { Menubar } from "@/components/shared/Menubar";
import { motion } from "framer-motion";
import Head from "next/head";
import { type FC, type PropsWithChildren } from "react";

type LayoutProps = {
  bg:
    | "bg-home-bg"
    | "bg-about-bg"
    | "bg-projects-bg"
    | "bg-skills-bg"
    | "bg-contact-bg";
};

export const Layout: FC<PropsWithChildren<LayoutProps>> = ({
  children,
  bg,
}) => {
  return (
    <>
      <Head>
        <title>Welcome to Hsunhsun</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${bg} relative flex h-full w-screen flex-col items-center justify-center`}
      >
        {/* <div className={`${bg} h-full w-full overflow-y-auto pb-24`}> */}
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ duration: 1 }}
          className="flex h-full w-full flex-col items-center justify-center overflow-y-auto pb-24"
        >
          {children}
        </motion.div>
        {/* </div> */}
        <Menubar />
      </div>
    </>
  );
};
