import { Menubar } from "@/components/shared/Menubar";
import { motion } from "framer-motion";
import Head from "next/head";
import { type FC, type PropsWithChildren } from "react";

type LayoutProps = {
  bg:
    | "bg-primary-hero-bg"
    | "bg-primary-vscode-bg"
    | "bg-primary-project-bg"
    | "bg-primary-skills-bg";
};

export const Layout: FC<PropsWithChildren<LayoutProps>> = ({
  children,
  bg,
}) => {
  return (
    <>
      <Head>
        <title>Welcome to Hsunhsun</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="relative flex h-screen w-screen flex-col items-center">
        <div className={`${bg} h-full w-full`}>
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ duration: 1 }}
            className="h-full w-full"
          >
            {children}
          </motion.div>
        </div>
        <Menubar />
      </div>
    </>
  );
};
